# Schema for the configuration files of the ecoindex module.

ecoindex.settings:
  type: config_object
  label: 'EcoIndex settings'
  mapping:
    minimum_score:
      type: integer
      label: 'Minimum score to alert contributor'
    required_to_publish:
      type: boolean
      label: 'Is required to publish content'

diff.plugin.settings.ecoindex_field_diff_builder:
  type: diff.plugin.settings_base
  label: 'Settings for EcoIndex field diff builder plugin'
  mapping:
    compare_score:
      type: integer
      label: 'Compare the score value'
    compare_grade:
      type: text
      label: 'Compare the grade value'
