# Schema for the configuration files of the ecoindex module.

ecoindex.settings:
  type: config_object
  label: 'EcoIndex settings'
  mapping:
    warning:
      type: string
      label: 'Warning ecoindex'
