# Schema for the configuration files of the ecoindex module.

ecoindex.settings:
  type: config_object
  label: 'EcoIndex settings'
  mapping:
    minimum_score:
      type: integer
      label: 'Minimum score to alert contributor'
    required_to_publish:
      type: boolean
      label: 'Is required to publish content'
